# Generated by Django 5.2.5 on 2025-08-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_alter_salon_lat_alter_salon_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
